name: hello

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run hello world one-line script
        run: echo "Hello, world!"
      - name: Run hello world multi-line script
        run: |
          echo "Hello, world!"
          echo "This is a test of the GitHub Actions workflow."
          echo "The current date and time is $(date)."
          echo "The current user is $(whoami)."
          echo "The current working directory is $(pwd)."
          echo "The contents of the current directory are:"
          ls -l